apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    {{- include "platform-lab.labels" (dict "root" $ "name" "api-gateway") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "platform-lab.selectorLabels" (dict "name" "api-gateway") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.apiGateway.containerPort }}
      targetPort: http
