apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway
  labels:
    {{- include "platform-lab.labels" (dict "root" $ "name" "api-gateway") | nindent 4 }}
data:
  {{- range $k, $v := .Values.apiGateway.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
