apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    {{- include "platform-lab.labels" (dict "root" $ "name" "user-service") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "platform-lab.selectorLabels" (dict "name" "user-service") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.userService.containerPort }}
      targetPort: http
