apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
  labels:
    {{- include "platform-lab.labels" (dict "root" $ "name" "user-service") | nindent 4 }}
data:
  {{- range $k, $v := .Values.userService.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
