name: user-service

on:
  push:
    branches: [main]
    paths:
      - "services/user-service/**"
      - "infrastructure/docker/**"
      - "messaging/rabbitmq/**"
      - "security/keycloak/**"
      - "security/sast/**"
      - "security/dependency-scan/**"
      - "security/image-scan/**"
      - "security/secret-scan/**"
      - "scripts/**"
      - ".github/workflows/user-service.yml"
      - ".github/workflows/_service.yml"
      - ".github/workflows/secret-scan.yml"
  pull_request:
    paths:
      - "services/user-service/**"
      - "infrastructure/docker/**"
      - "messaging/rabbitmq/**"
      - "security/keycloak/**"
      - "security/sast/**"
      - "security/dependency-scan/**"
      - "security/image-scan/**"
      - "security/secret-scan/**"
      - "scripts/**"
      - ".github/workflows/user-service.yml"
      - ".github/workflows/_service.yml"
      - ".github/workflows/secret-scan.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: user-service-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/_service.yml
    permissions:
      contents: read
      packages: write
      security-events: write
      actions: read
    with:
      service: user-service
      smoke-deps: keycloak
      smoke-urls: http://localhost:3001
